search_query = """Use `search_query` when you need to find the most relevant results to a natural language query, especially in cases where property filters alone cannot capture user intent or when you want to enhance filtered results with semantic understanding. Unlike exact property filters (such as `text_property_filter`, `int_property_filter`, or `boolean_property_filter`), which require precise matches on property values, `search_query` interprets the meaning behind the words, handling synonyms, context, misspellings, and related concepts.

**Examples of when to use `search_query`:**

1. **Synonyms and Related Terms**: If a user searches for "energy-efficient refrigerators," a simple text filter on the product description may miss items labeled as "eco-friendly fridges." `search_query` understands that "energy-efficient" and "eco-friendly" are related concepts, and "refrigerators" and "fridges" are synonyms, thus returning more comprehensive results.

2. **Natural Language Questions**: When a user asks, "What laptops are good for gaming and under $1,000?" filters alone may struggle to interpret this multi-faceted query. `search_query` can parse the intent, understanding that the user wants gaming-capable laptops within a specific price range, even if those exact phrases aren't in the product properties.

3. **Misspellings and Variations**: A search for "wireless headphonez" with a misspelling may yield no results using exact filters. `search_query` can recognize and correct misspellings, returning relevant results for "wireless headphones."

4. **Contextual Understanding**: If a user searches for "comfortable chairs for back pain," filters might not capture the nuance unless there's a specific property labeled "suitable for back pain." `search_query` can semantically match products designed to alleviate back discomfort, even if the exact terms don't match.

5. **Enhancing Filtered Results**: You can combine `search_query` with property filters to refine results further. For example, after applying an `int_property_filter` to select houses with "price < $500,000," you can use `search_query` with "family-friendly neighborhood with good schools" to find listings that match both the filter and the semantic intent.

In situations where user queries are complex, involve synonyms, or require an understanding of context and intent beyond exact property matches, `search_query` is the ideal choice. It excels at capturing the essence of what the user is looking for, providing relevant results that property filters or aggregations alone cannot achieve."""

text_property_filter = """Use `text_property_filter` when you need to retrieve objects that match a specific condition on a text-valued property with exact or pattern-based matching. Unlike `search_query`, which handles natural language input and semantic matching to capture user intent, `text_property_filter` strictly matches the specified text condition without interpreting synonyms or context. This makes it ideal for precise filtering tasks, such as retrieving all items with the category 'Electronics'. If you require exact matching on a text property rather than semantic relevance or data aggregation (as provided by `text_property_aggregation`), `text_property_filter` is the appropriate API to use."""

int_property_filter = """Use `int_property_filter` when you need to return objects that match a specific numerical condition on an integer-valued property, such as finding all products with a price less than $100. Unlike `search_query`, which is designed for semantic matching based on user intent, `int_property_filter` provides precise numerical filtering without interpreting natural language queries or semantic meaning. This API is ideal when exact numerical conditions are required. If your goal is to filter data based on specific integer values or ranges rather than semantic search or data aggregation (as offered by `int_property_aggregation`), `int_property_filter` is the suitable choice."""

boolean_property_filter = """Use `boolean_property_filter` when you need to retrieve objects that match a specific true or false condition on a boolean-valued property, such as selecting all users who are 'subscribed' or items that are 'in stock'. Unlike `search_query`, which interprets natural language input to find semantically relevant results, `boolean_property_filter` strictly filters records based on the exact true or false value of a property. This API does not handle synonyms, context, or fuzzy matching. If you need precise filtering based on a boolean property rather than semantic search or aggregation (as provided by `boolean_property_aggregation`), `boolean_property_filter` is the appropriate API to use."""

text_property_aggregation = """Use `text_property_aggregation` when you need to compute aggregate values over a text-valued property, such as counting the number of items in each category or listing all unique tags associated with products. Unlike `search_query`, which retrieves individual records based on semantic relevance to a query, `text_property_aggregation` provides summary information over text properties without retrieving individual records. This API does not handle natural language input or fuzzy matching. If your goal is to generate reports or insights by aggregating text data rather than searching or filtering for specific records (as done with `text_property_filter`), `text_property_aggregation` is the suitable API to use."""

int_property_aggregation = """Use `int_property_aggregation` when you need to perform aggregate calculations over an integer-valued property, such as computing the average price of items, total sales, or maximum score. Unlike `search_query`, which focuses on retrieving relevant records based on user intent and semantic meaning, `int_property_aggregation` provides numerical insights over a dataset without processing natural language queries or retrieving individual records. If you require numerical summaries and statistics over integer data rather than searching or filtering (as with `int_property_filter`), `int_property_aggregation` is the appropriate API to use."""

boolean_property_aggregation = """Use `boolean_property_aggregation` when you need to aggregate data over a boolean-valued property, such as counting the number of items that are 'in stock' versus 'out of stock' or determining the percentage of users who are 'verified'. Unlike `search_query`, which retrieves results based on semantic understanding, `boolean_property_aggregation` provides summary statistics over boolean properties without processing natural language input or retrieving individual records. If your objective is to gain insights by aggregating boolean data rather than searching or filtering specific records (as done with `boolean_property_filter`), `boolean_property_aggregation` is the suitable API to use."""

groupby = """Use `groupby` when you need to organize or segment results based on the values of a specific property, creating groups of records that share the same property value. For example, grouping sales data by region or products by category. Unlike `search_query`, which retrieves relevant records based on semantic queries, `groupby` reorganizes the dataset without interpreting natural language or semantic meaning. It does not filter out records like property filters (e.g., `text_property_filter`, `int_property_filter`, `boolean_property_filter`) nor does it perform aggregate computations unless combined with aggregation functions. If you need to segment your data into groups based on property values rather than searching, filtering, or aggregating data, `groupby` is the appropriate API to use."""