---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.0
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - ./backups:/tmp/backups
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      RERANKER_INFERENCE_API: 'http://reranker-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,reranker-transformers,text2vec-openai,generative-openai'
      OPENAI_APIKEY: 'sk-foobar'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_EXPERIMENTAL_BM25: 'true'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: '0'
  reranker-transformers:
    image: semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
    environment:
      ENABLE_CUDA: '0'
...
