apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: llama-2-7b-weaviate-gorilla-api-split
spec:
  # image: substratusai/model-trainer-huggingface
  build:
    git:
      url: https://github.com/substratusai/images
      path: model-trainer-huggingface
      branch: push-to-hub-training-log
  baseModel:
    name: llama-2-7b
  params:
    # See HuggingFace transformers.TrainingArguments for all parameters
    # https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments
    num_train_epochs: 1
    dataset_urls: https://huggingface.co/datasets/weaviate/WeaviateGraphQLGorilla-APISplit-Train/resolve/main/WeaviateGorilla-APIsplit-train.json
    push_to_hub: substratusai/weaviate-gorilla-v4-api-split
    hugging_face_hub_token: ${HUGGINGFACE_TOKEN}
    save_steps: 5
    prompt_template: |
      ## Instruction
      Your task is to write GraphQL for the Natural Language Query provided. Use the provided API reference and Schema to generate the GraphQL. The GraphQL should be valid for Weaviate.

      Only use the API reference to understand the syntax of the request.

      ## Natural Language Query
      {nlcommand}

      ## Schema
      {schema}

      ## API reference
      {apiRef}

      ## Answer
      {output}

  resources:
    gpu:
      count: 4
      type: nvidia-l4
